#ifndef EZGRAVERLIB_GLOBAL_H
#define EZGRAVERLIB_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(EZGRAVERLIB_LIBRARY)
#  define EZGRAVERLIBSHARED_EXPORT Q_DECL_EXPORT
#else
#  define EZGRAVERLIBSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // EZGRAVERLIB_GLOBAL_H
