#ifndef EZGRAVERCORE_GLOBAL_H
#define EZGRAVERCORE_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(EZGRAVERCORE_LIBRARY)
#  define EZGRAVERCORESHARED_EXPORT Q_DECL_EXPORT
#else
#  define EZGRAVERCORESHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // EZGRAVERCORE_GLOBAL_H
